### ISSUE TITLE
Insert videos in the pdf?

### ISSUE THREAD

**Issue by navidcy** [ClimateFluidPhysics-ANU/ANU-presentation#1]
It would be nice if we can insert videos in the presentation that would play when we open the pdf file with Acrobat. I had a way of doing this somewhere... I'll try to find it and include it in the template.

**Comment by josuemtzmo** [comment]
Hello Navid, Actually the video should work within Acrobat, the only thing you need to do is to able the video future. Usually, a warning will pop up once you are on the slide with the video.

**Comment by navidcy** [comment]
Yes... I hadn't opened it with Acrobat so I missed that. Nice.
